_core:
  default_config_hash: CXhei_vpaZk-3f_Mj2cH0YmpK-ZpKHoSzVA3yZrDq0g
definitions:
  contact__site_page:
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
    enabled: true
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -51
    expanded: false
    enabled: false
  entity__field_storage_config__collection:
    menu_name: admin
    parent: system.admin_reports
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:views_ui__field_list':
    menu_name: admin
    parent: entity.field_storage_config.collection
    weight: 0
    expanded: false
    enabled: false
  dblog__access_denied:
    menu_name: admin
    parent: system.admin_reports
    weight: 0
    expanded: false
    enabled: false
  dblog__page_not_found:
    menu_name: admin
    parent: system.admin_reports
    weight: 0
    expanded: false
    enabled: false
  dblog__search:
    menu_name: admin
    parent: system.admin_reports
    weight: 0
    expanded: false
    enabled: false
  views_ui__reports_plugins:
    menu_name: admin
    parent: system.admin_reports
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:user__role_add':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.collection'
    weight: -50
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_form__anonymous':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.collection'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_permissions_form__anonymous':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.edit_form.anonymous'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_form__authenticated':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.collection'
    weight: 1
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_permissions_form__authenticated':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.edit_form.authenticated'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_form__content_editor':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.collection'
    weight: 2
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__delete_form__content_editor':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.edit_form.content_editor'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_permissions_form__content_editor':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.edit_form.content_editor'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_form__administrator':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.collection'
    weight: 3
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__delete_form__administrator':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.edit_form.administrator'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:entity__user_role__edit_permissions_form__administrator':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:entity.user_role.edit_form.administrator'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:update__theme_install':
    menu_name: admin
    parent: system.themes_page
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:system__theme_settings':
    menu_name: admin
    parent: system.themes_page
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:system__theme_settings_theme__claro':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:system.theme_settings'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:system__theme_settings_theme__gin':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:system.theme_settings'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:system__theme_settings_theme__surface':
    menu_name: admin
    parent: 'admin_toolbar_tools.extra_links:system.theme_settings'
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:update__theme_update':
    menu_name: admin
    parent: system.themes_page
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:update__module_install':
    menu_name: admin
    parent: system.modules_list
    weight: 0
    expanded: false
    enabled: false
  system__modules_uninstall:
    menu_name: admin
    parent: system.modules_list
    weight: 0
    expanded: false
    enabled: false
  'admin_toolbar_tools__extra_links:update__module_update':
    menu_name: admin
    parent: system.modules_list
    weight: 0
    expanded: false
    enabled: false
  user__page:
    enabled: false
    menu_name: account
    parent: ''
    expanded: false
    weight: -10
