_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  address: 0
  admin_toolbar: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  big_pipe: 0
  block: 0
  block_content: 0
  block_field: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor5: 0
  components: 0
  config: 0
  content_moderation: 0
  date_popup: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  entity_reference_revisions: 0
  entity_usage: 0
  environment_indicator: 0
  estimated_read_time: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  gin_toolbar: 0
  image: 0
  imagemagick: 0
  layout_discovery: 0
  layout_options: 0
  layout_paragraphs: 0
  layout_paragraphs_library: 0
  link: 0
  linkit: 0
  media: 0
  media_entity_file_replace: 0
  media_library: 0
  media_library_edit: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs_library: 0
  path: 0
  path_alias: 0
  rebuild_cache_access: 0
  responsive_image: 0
  scheduler: 0
  scheduler_content_moderation_integration: 0
  search: 0
  simple_sitemap: 0
  smart_trim: 0
  sophron: 0
  style_options: 0
  surface_admin: 0
  svg_image: 0
  system: 0
  tablefield: 0
  tablefield_cellspan: 0
  taxonomy: 0
  telephone: 0
  template_whisperer: 0
  text: 0
  token: 0
  token_or: 0
  toolbar: 0
  twig_field_value: 0
  twig_tweak: 0
  update: 0
  user: 0
  viewfield: 0
  views_ui: 0
  workbench_access: 0
  workbench_email: 0
  workflows: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  minimal: 1000
theme:
  claro: 0
  gin: 0
  surface: 0
profile: minimal
