_core:
  default_config_hash: AXUBMTvVtpcNp0jKjDaWjSHqMy6HjuUf7j4yVbXgazI
local_task_enabled_entity_types:
  - paragraphs_library_item
track_enabled_source_entity_types:
  - node
  - content_moderation_state
  - block_content
  - menu_link_content
  - media
  - paragraph
  - paragraphs_library_item
  - taxonomy_term
  - path_alias
track_enabled_target_entity_types:
  - node
  - content_moderation_state
  - block_content
  - menu_link_content
  - media
  - paragraph
  - paragraphs_library_item
  - taxonomy_term
  - path_alias
track_enabled_plugins:
  - media_embed
  - link
  - layout_builder
  - html_link
  - ckeditor_image
  - entity_embed
  - entity_reference
  - linkit
  - dynamic_entity_reference
  - block_field
track_enabled_base_fields: false
site_domains: {  }
edit_warning_message_entity_types:
  - media
  - paragraphs_library_item
delete_warning_message_entity_types:
  - media
  - paragraphs_library_item
usage_controller_items_per_page: 25
