_core:
  default_config_hash: jikSRsiHKpx-02cLfUrjHLE2kIA4-NP31cWe2cVP-X4
favicon:
  path: ''
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: false
  node_user_picture: false
logo:
  use_default: true
site_branding: default
site_theme: dgsom
site_menu: dropdown
header_logo:
  - '34'
footer_logo: {  }
facebook_url: ''
twitter_url: ''
instagram_url: ''
youtube_url: ''
linkedin_url: ''
