_core:
  default_config_hash: jikSRsiHKpx-02cLfUrjHLE2kIA4-NP31cWe2cVP-X4
favicon:
  use_default: true
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: true
  node_user_picture: false
logo:
  use_default: true
site_branding: default
