_core:
  default_config_hash: jikSRsiHKpx-02cLfUrjHLE2kIA4-NP31cWe2cVP-X4
favicon:
  path: ''
  use_default: false
features:
  comment_user_picture: false
  comment_user_verification: false
  favicon: false
  node_user_picture: false
logo:
  path: ''
  use_default: false
site_branding: default
site_menu: default
header_logo: {  }
footer_logo: {  }
site_theme: default
